### ISSUE TITLE
openhab-4.x support

### ISSUE THREAD

**Issue by JacekKac** [delid4ve/openhab-sonoff#26]
Please

**Comment by proggprod** [comment]
Pretty please

**Comment by FrancescoTalotta** [comment]
That would be great for the community

**Comment by jgesser** [comment]
I just released a binary for OH4 in my fork, please test and let me know if it is working as expected:
https://github.com/jgesser/openhab-3.x-sonoff/releases/tag/v4.0.0-SNAPSHOT

**Comment by 3volution91** [comment]
device discovery not working on OH4. binding not appearing when trying to add new device. thankyou

**Comment by marsic-84** [comment]
Still the same:  binding not appearing when trying to add new device.

**Comment by JacekKac** [comment]
maybe there is a workarround to skip the discovery ? can i somehow copy the cache files from other machine / edit them ?> 
i have placed a file with my device
pi@raspberrypi:~ $ ls /var/lib/openhab/sonoff/
100104334c.txt
but no luck
